<<<<<<< HEAD
version: "2"
output:
  formats:
    text:
      path: stdout
  path-prefix: .
=======
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/testcontainers)
>>>>>>> tcgo/main
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - revive
    - testifylint
    - thelper
    - usestdlibvars
<<<<<<< HEAD
  settings:
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
=======
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    errorlint:
      asserts: true
      comparison: true
      errorf: true
      errorf-multi: true
>>>>>>> tcgo/main
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: dot-imports
        - name: early-return
          arguments:
            - preserveScope
        - name: empty-block
        - name: error-naming
          disabled: true
        - name: error-return
        - name: error-strings
          disabled: true
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - preserveScope
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
          disabled: true
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: time-naming
        - name: unexported-return
          disabled: true
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: var-declaration
        - name: var-naming
          arguments:
            - - ID
            - - VM
            - - upperCaseConst: true
<<<<<<< HEAD
    testifylint:
      enable-all: true
      disable:
        - float-compare
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/docker)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
=======
    staticcheck:
      checks:
        - all
    testifylint:
      disable:
        - float-compare
        - go-require
      enable-all: true
output:
  formats:
    text:
      path: stdout
  path-prefix: .
version: "2"
>>>>>>> tcgo/main
