name: Run benchmarks for a Go project
run-name: "${{ inputs.project-directory }}"

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
        default: "."
        description: "The directory where the Go project is located."

permissions:
  contents: read
  # we need write permission to be able to post comments to pull request
  pull-requests: write

jobs:
  Compare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: ${{ inputs.project-directory }}/go.mod
          cache-dependency-path: ${{ inputs.project-directory }}/go.sum
        id: go

      - name: Run Benchmark
        working-directory: ${{ inputs.project-directory }}
        run: set -o pipefail; go test ./... -benchmem -run=^$ -bench . | tee output.txt

      - name: Check benchmark output and exit gracefully if not found
        id: check-benchmarks
        working-directory: ${{ inputs.project-directory }}
        run: |
          if [ ! -f output.txt ]; then
            echo "No benchmarks found. Workflow completed successfully."
            echo "benchmarks_found=false" >> $GITHUB_OUTPUT
          else
            echo "benchmarks_found=true" >> $GITHUB_OUTPUT
          fi

      # NOTE: Benchmarks could change with different CPU types
      - name: Get GitHub Runner System Information
        if: ${{ steps.check-benchmarks.outputs.benchmarks_found == 'true' }}
        uses: kenchan0130/actions-system-info@1a16c1960cecc14b8de80e3e11a42f3f9f037593 # v1.3
        id: system-info

      - name: Get Main branch SHA
        if: ${{ steps.check-benchmarks.outputs.benchmarks_found == 'true' }}
        id: get-main-branch-sha
        run: |
          SHA=$(git rev-parse origin/main)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Get Benchmark Results from main branch
        if: ${{ steps.check-benchmarks.outputs.benchmarks_found == 'true' }}
        id: cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ./${{ inputs.project-directory }}/cache
          key: ${{ steps.get-main-branch-sha.outputs.sha }}-${{ runner.os }}-${{ steps.system-info.outputs.cpu-model }}-${{ inputs.project-directory }}-benchmark

      # This will only run if we have Benchmark Results from main branch
      - name: Compare PR Benchmark Results with main branch
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20
        if: ${{ steps.cache.outputs.cache-hit == 'true' && steps.check-benchmarks.outputs.benchmarks_found == 'true' }}
        with:
          tool: 'go'
          output-file-path: ./${{ inputs.project-directory }}/output.txt
          external-data-json-path: ./${{ inputs.project-directory }}/cache/benchmark-data.json
          # Do not save the data (This allows comparing benchmarks)
          save-data-file: false
          fail-on-alert: true
          # Comment on the PR if the branch is not a fork
          comment-on-alert: ${{ github.event.pull_request.head.repo.fork == false }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          alert-threshold: "150%"

      - name: Store Benchmark Results for main branch
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20
        if: ${{ github.ref_name == 'main' && steps.check-benchmarks.outputs.benchmarks_found == 'true' }}
        with:
          tool: 'go'
          output-file-path: ./${{ inputs.project-directory }}/output.txt
          external-data-json-path: ./${{ inputs.project-directory }}/cache/benchmark-data.json
          # Save the data to external file (cache)
          save-data-file: true
          fail-on-alert: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          alert-threshold: "150%"

      - name: Update Benchmark Results cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        if: ${{ github.ref_name == 'main' }}
        with:
          path: ./${{ inputs.project-directory }}/cache
          key: ${{ steps.get-main-branch-sha.outputs.sha }}-${{ runner.os }}-${{ steps.system-info.outputs.cpu-model }}-${{ inputs.project-directory }}-benchmark