name: Run lint for a Go project
run-name: "${{ inputs.project-directory }}"

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
        default: "."
        description: "The directory where the Go project is located."

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint-go-project:
    name: "lint: ${{ inputs.project-directory }}"
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
<<<<<<< HEAD
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
=======
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
>>>>>>> tcgo/main
        with:
            go-version-file: "${{ inputs.project-directory == '' && '.' || inputs.project-directory }}/go.mod"
            cache-dependency-path: "${{ inputs.project-directory == '' && '.' || inputs.project-directory }}/go.sum"
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v2.0.2
          # Optional: working directory, useful for monorepos
          working-directory: ${{ inputs.project-directory }}

<<<<<<< HEAD
=======
      - name: generate
        working-directory: ./${{ inputs.project-directory }}
        shell: bash
        run: |
          make generate
          git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]

>>>>>>> tcgo/main
      - name: modTidy
        working-directory: ./${{ inputs.project-directory }}
        shell: bash
        run: |
<<<<<<< HEAD
          go mod tidy
=======
          make tidy
>>>>>>> tcgo/main
          git --no-pager diff && [[ 0 -eq $(git status --porcelain | wc -l) ]]
